on: push
name: Build
jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - uses: actions-rs/cargo@v1
              with:
                  command: test
